baseURL = 'https://galle0nn.github.io/'
languageCode = 'en-us'
theme = 'friend'
paginate = 3


[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "homepage"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true


[languages]
  [languages.en]
    title = "The Shipyard"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = ""
    writtenBy = "Written by"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave  empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "cd /home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "analysis"
        name = "Malware Analysis"
        url = "/malware-analysis"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "documents"
        name = "Documents"
        url = "/documents"
        weight = 2

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/_galle0n"

  [[params.social]]
    name = "github"
    url  = "https://github.com/galle0nn"

  [[params.social]]
    name = "email"
    url  = "mailto:galle0nn@protonmail.com"
